name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when I have to manually...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        I would like a command like:
        $ forkspacer workspace import --from-helm
      render: shell
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also thought about using kubectl directly, but...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature benefit you or other users?
      placeholder: This would help me by allowing...

  - type: dropdown
    id: willingness
    attributes:
      label: Are you willing to contribute this feature?
      description: Would you be interested in submitting a PR?
      options:
        - "Yes, I'd like to implement this"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or command mockups
      placeholder: |
        Example usage:
        $ forkspacer workspace create dev --interactive
      render: shell
