name: Question
description: Ask a question about using the CLI
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        Before asking, please check:
        - [Documentation](https://github.com/forkspacer/cli#documentation)
        - [Existing Issues](https://github.com/forkspacer/cli/issues)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've tried
      placeholder: |
        I tried running:
        $ forkspacer workspace create...
        But I'm not sure how to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Anything else that might be helpful
